apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: eventbus
      protocol: TCP
      port: 4009
      targetPort: 4009
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: post
      protocol: TCP
      port: 4002
      targetPort: 4002
    - name: client
      protocol: TCP
      port: 3110
      targetPort: 3110
    - name: classrooms
      protocol: TCP
      port: 4001
      targetPort: 4001